POST /death/2
Content-Type: application/json
Host: localhost:8080

{
  "residentSerialNo": 0,
  "birthDeathCode": "사망",
  "reportDate": "22001114",
  "deathReportQualificationsCode": "동거친족",
  "phoneNumber": "010111111111"
}

###

PUT /death/2/0
Content-Type: application/json
Host: localhost:8080

{
  "emailAddress": "ehdgns07@gmail.com",
  "phoneNumber": "010-1111-1111",
  "deathReportQualificationsCode": "동거친족"
}

###
DELETE /death/2/0
Host: localhost:8080
